#!/bin/bash

# TODO:
# * support cmd/args from pod spec
# * tini (bind mount?)
# * better log output
# * better system service sidecar visibility
# * use the image made by newt instead of hardcode
# * where does titus-inits come from?

set -eu -o pipefail
run_id=$(od -N 16 -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}')
log() {
    echo -e "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $1" >&2
}

docker_container_name="titus-compose-${run_id}"
terminate_titus_docker() {
    log "## Titus compose run exited. Terminating docker container"
    docker logs 843863f1-41a2-4a73-89bc-89c506bc1e14 || true
    docker exec "$docker_container_name" journalctl > titus-compose.log || true
    log "## Dumpped logs to 'titus-compose.log'"
    docker logs -f $docker_container_name &
    log "Stopping container: $docker_container_name"
    docker stop "$docker_container_name" 2>/dev/null || true
    log "Container stopped (rc: $?)"
}

trap terminate_titus_docker EXIT

if ! [[ -f "${PWD}/pod.json" ]]; then
  echo "need ${PWD}/pod.json"
  exit 1
fi

log "Running a docker daemon named $docker_container_name"
docker stop "/843863f1-41a2-4a73-89bc-89c506bc1e14" || true
docker rm "/843863f1-41a2-4a73-89bc-89c506bc1e14" || true
docker run -ti --privileged --security-opt seccomp=unconfined -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
  -w / -v ${PWD}:/work \
  -v ${PWD}/pod.json:/etc/titus-executor/pod.json \
  -v /Users/kyleanderson/Projects/titus-executor/build/bin/linux-amd64/:/apps/titus-executor/bin/:ro \
  -v /var/run/docker.sock:/var/run/docker.sock:rw \
  -e DOCKER_REGISTRY="registry.us-east-1.streamingtest.titus.netflix.net:7002" \
  -e LOGVIEWER_SERVICE_IMAGE="/baseos/nflx-adminlogs@sha256:fe27edfe317163b59e3afaad9a0b5e93e4d731b03bf79650abb4490b8a0fece6" \
  -e SSHD_SERVICE_IMAGE="/titusoss/titus-sshd@sha256:6f6f89250771a50e13d5a3559712defc256c37b144ca22e46c69f35f06d848a0" \
  -e METATRON_SERVICE_IMAGE="/ps/titus-metatron-identity" \
  -e PROXYD_SERVICE_IMAGE="/ipc/proxyd-rootless-candidate@sha256:9d5e5292015856b60cfcca51024cdceba1b07f9fe952b96ccac4b741aab43708" \
  -e ABMETRIX_SERVICE_IMAGE="/baseos/nflx-abmetrix-titus@sha256:0b01b2d74b9b62c7ad85007da0491d40c1f80e5812676667bedcade2448f24e3" \
  --rm --name "$docker_container_name" \
  -d \
  -e SHORT_CIRCUIT_QUITELITE=true --label "$run_id" titusoss/titus-agent

log "Copying test metatron certs to their correct location"
docker exec "$docker_container_name" /metatron/certificates/setup-metatron-certs.sh

log "Running titus-compose in $docker_container_name"
docker exec "$docker_container_name" /apps/titus-executor/bin/titus-standalone \
   --log-level=debug \
   -pod /etc/titus-executor/pod.json || true

log "press enter to finish"
read foo
